(.devops) [tornado@sfiteml012 project-ml-microservice-kubernetes]$ ./run_kubernetes.sh
Error from server (AlreadyExists): pods "ml" already exists
NAME   READY   STATUS    RESTARTS   AGE
ml     1/1     Running   0          6m57s
Forwarding from 0.0.0.0:8000 -> 80
Handling connection for 8000
Handling connection for 8000
[tornado@sfiteml012 project-ml-microservice-kubernetes]$ kubectl logs ml
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 716-831-663
[2022-12-06 06:18:01,035] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-12-06 06:18:01,050] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-06 06:18:01,061] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-06 06:18:01,065] INFO in app: Prediction payload:
[20.35373177134412]
127.0.0.1 - - [06/Dec/2022 06:18:01] "POST /predict HTTP/1.1" 200 -
[2022-12-06 06:27:33,936] INFO in app: JSON payload:
{'CHAS': {'0': 0}, 'RM': {'0': 6.575}, 'TAX': {'0': 296.0}, 'PTRATIO': {'0': 15.3}, 'B': {'0': 396.9}, 'LSTAT': {'0': 4.98}}
[2022-12-06 06:27:33,950] INFO in app: Inference payload DataFrame:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-06 06:27:33,963] INFO in app: Scaling Payload:
   CHAS     RM    TAX  PTRATIO      B  LSTAT
0     0  6.575  296.0     15.3  396.9   4.98
[2022-12-06 06:27:33,966] INFO in app: Prediction payload:
[20.35373177134412]
127.0.0.1 - - [06/Dec/2022 06:27:33] "POST /predict HTTP/1.1" 200 -
